WIP: Parse tags starting with digits and containing spaces (close #1072)
silverbulletmd/silverbullet pull request #1116
Opened 2024-10-14 18:39 UTC by Maarrk

I'd suggest to continue discussion in #1072

2024-10-17 16:54 UTC, zefhemel requested changes
Added a few comments, but looking forward to get this in!

2024-10-17 16:54 UTC, zefhemel commented on plug-api/lib/tags.ts
> +import { hashtagName } from "$common/markdown_parser/parser.ts";
The idea of `plug-api/*` is that these can be liberally imported from plugs without pulling in too much random code. In this case you're importing basically the entire markdown parser + all lezer parser code, not a good idea. Maybe you can move the `hashtagName` and related functions even to this very file (tags.ts) and import them into the markdown parser instead?

2024-10-17 16:54 UTC, zefhemel commented on common/markdown_parser/parser.ts
> +export function hashtagText(name: string): string {
What about `renderHashtag`?

2024-10-17 16:54 UTC, zefhemel commented on common/markdown_parser/parser.ts
> +export function hashtagName(text: string): string {
what about `extractHashtag`?

2024-10-17 16:54 UTC, zefhemel commented on common/markdown_parser/parser.ts
> +  const simple: string = "#".concat(name);
What about simply `const simple = "#" + name"`?

2024-10-17 18:24 UTC, Maarrk commented on common/markdown_parser/parser.ts
> +  const simple: string = "#".concat(name);
Changed. I had had issues with `+` for strings in typescript, still don't know where I can and can't use it.

2024-10-17 18:28 UTC, Maarrk commented on plug-api/lib/tags.ts
> +import { hashtagName } from "$common/markdown_parser/parser.ts";
That's an area in which I have very little experience, and I'm glad to learn. Now everything is importing `markdown_parser/constants.ts` instead. Suddenly it makes sense why this module exists :smile:

2024-10-19 09:20 UTC, zefhemel commented on plug-api/lib/tags.ts
> +import { tagRegex } from "$common/markdown_parser/constants.ts";
The problem we have now is that this means that `$common` needs to be defined in any plug relying on this file, which will be the case for all the builtins, but not for external plugs. Two options: either move the constant into plug-api/lib (again: I think this very file tags.ts would be fine) or use a relative path: `../../common/markdown_parser/...` instead.

2024-10-20 10:39 UTC, zefhemel commented
Ok you know what, let me just merge this as it and fix it on main.

2024-10-20 10:39 UTC, merged

2024-10-20 11:08 UTC, Maarrk commented
OK, thanks! I'll write down the changes I needed to do here for future PRs

2024-10-20 11:47 UTC, zefhemel commented
I hope you're taking a note in SilverBullet.