Implement native sharing
silverbulletmd/silverbullet pull request #1158
Opened 2024-11-17 23:26 UTC by nightscape

2024-11-18 06:54 UTC, nightscape commented
Oh, the way it is currently implemented does not work in offline mode, which makes it 80% less useful...

2024-11-18 08:15 UTC, nightscape commented on plugs/share/share.plug.yaml
> +      - http:request:/share_target
@zefhemel I guess just specifying `env: client` here is not enough to trigger `handleShareTarget` through an incoming http request, right?
Is there already logic to delegate `http:request` events to plugs on the client side?
It looks like this would need to be done in `service_worker.ts` which currently only handles read requests.
Do you think it's a good idea to enhance `service_worker.ts` with `dispatchEvent` logic similar to `http_server.ts`?

2024-11-26 00:10 UTC, nightscape commented on plugs/share/share.plug.yaml
> +      - http:request:/share_target
@zefhemel ping 😉

2024-12-14 08:44 UTC, zefhemel commented on plugs/share/share.plug.yaml
> +      - http:request:/share_target
RIght. Right now handling HTTP requests through a service worker (so fully locally and therefore offline) is not possible. It's technically possible to do, but it's not there at this moment.

2024-12-14 08:51 UTC, zefhemel commented
Sorry for the huge delay of this.

I like this feature, but I'd implement it slightly differently, if this would work (I don't have an environment to test this on, because I think this is an Android feature only?) I'd implement the endpoint handling "hardcoded" in the service worker. That is: in the `fetch` event handler, decide on some URL (like `/.share` or something), and put the logic in the service worker directly rather than in the share plug. I feel this is functionality that deserves a place directly in the SB core, not so much in a plug (it needs to be hardcoded in the manifest anyway), and implemented in the service worker it can also be done (I think) in a way that works both in online and offline mode.

2024-12-14 08:52 UTC, zefhemel requested changes
Sorry for the huge delay of this.

I like this feature, but I'd implement it slightly differently, if this would work (I don't have an environment to test this on, because I think this is an Android feature only?) I'd implement the endpoint handling "hardcoded" in the service worker. That is: in the `fetch` event handler, decide on some URL (like `/.share` or something), and put the logic in the service worker directly rather than in the share plug. I feel this is functionality that deserves a place directly in the SB core, not so much in a plug (it needs to be hardcoded in the manifest anyway), and implemented in the service worker it can also be done (I think) in a way that works both in online and offline mode.

2024-12-14 08:53 UTC, zefhemel commented
A head's up: working with service worker is a bit of a pain in terms of reload behavior. In Chrome, you can have the service worker update on every reload:

![CleanShot 2024-12-14 at 09 52 48@2x](https://github.com/user-attachments/assets/01da7101-6a03-4e1c-9466-dbf641c58e8e)

Still you probably need to reload your page a few times after every change to make sure you got the new service worker running before deciding things don't work ;)

2024-12-14 09:33 UTC, nightscape commented on plugs/share/share.plug.yaml
> +      - http:request:/share_target
Would `service_worker.ts` be the right place? Do you see any issues with using a similar approach as on the server-side, i.e. checking the plugs if one of them wants to handle the URL?

2025-03-06 17:29 UTC, closed without merging