WIP - initial admonition support (github format)
silverbulletmd/silverbullet pull request #186
Opened 2022-12-11 10:30 UTC by christian-schulze

Resolves #67

Adds initial markdown support for Admonitions (using github syntax):
```
> **note** Note Admonition
> This is a Note Admonition
```
And:
```
> **warning** Warning Admonition
> This is a Warning Admonition
```

2022-12-11 10:54 UTC, zefhemel requested changes
Nice start, have a look at my comments! Haven’t been able to actually test this yet (not behind a computer) but this should already be useful.

2022-12-11 10:54 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +        if (type.name !== "QuoteMark") {
This means: do the following for every single AST node that is NOT a quotemark, is this what you want? If you don’t want to match a quote mark (which is just the `>` symbol, its parent is probably something more useful), there’s probably a parent element (can’t remember from the top of my head and can’t check now, perhaps `Blockquote` or similar?) that is more restrictive? What you do here will likely work but is very expensive.

2022-12-11 10:54 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +          const regexResults = text.match(/^>( *)\*{2}(Note|Warning)\*{2}( *)(.*)(?:\n([\s\S]*))?/im);
Style thing: let’s lift this regex to a `const` at the top level of the file.

2022-12-11 10:54 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +          const admonitionContent: string = regexResults[5] || '';
Style suggestion: perhaps replace this with a construct like `const [preSpaces, admonintionType, postSpaces, …] = regexResults;` ? See other files in this folder for examples.

2022-12-11 10:54 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +          if (!isCursorInRange(state, [iconRange.fromNoSpaces, iconRange.to - 1])) {
Once you make the `type` match (earlier comment) more specific, you probably want to back out of this whole logic if the cursor is in range earlier. That is: lift the `if(isCursorInRange(state, from, to)) { return; }` further to the top because likely you don’t want to show any widgets when your cursor is anywhere in a blockquote, right?

2022-12-11 10:58 UTC, christian-schulze commented on web/cm_plugins/admonition.ts
> +        if (type.name !== "QuoteMark") {
Yep this is definitely a mistake on my part, my intention was definitely to match, not skip. Oddly enough it seems to be working...I will fix soon.

2022-12-11 11:01 UTC, christian-schulze commented on web/cm_plugins/admonition.ts
> +          if (!isCursorInRange(state, [iconRange.fromNoSpaces, iconRange.to - 1])) {
So this plugin is dynamically applying styles to the existing editable area, its only changing colours and a few other minor things. This block is for the icon, if your cursor is within the `**note**` or `**warning**` text it will skip replacing it with the icon

2022-12-11 11:03 UTC, christian-schulze commented on web/cm_plugins/admonition.ts
> +          if (!isCursorInRange(state, [iconRange.fromNoSpaces, iconRange.to - 1])) {
I have a larger regex further up which bails out if it doesn't match an Admonition formatted block

2022-12-11 11:35 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +          if (!isCursorInRange(state, [iconRange.fromNoSpaces, iconRange.to - 1])) {
Alright, I haven’t been able to try how it works in practice, so I was just making assumptions based on the code.

2022-12-11 11:37 UTC, christian-schulze commented on web/cm_plugins/admonition.ts
> +        if (type.name !== "QuoteMark") {
Yep have changed to `Blockquote`, works correctly. Will push updates in a few minutes.

2022-12-11 11:50 UTC, zefhemel commented
Looks reasonable enough from the code perspective, I’ll check it out (literally) later to see if actually works 😉 before merging (QA you know).

2022-12-11 11:54 UTC, christian-schulze commented
> Looks reasonable enough from the code perspective, I’ll check it out (literally) later to see if actually works wink before merging (QA you know). Or is there more you’d want to change (since it’s still marked as WIP).

I think there are many things that can be added, more types, different syntax support, custom types etc. But that can be for future PR's.
If you don't find any bugs am happy for you to merge. Will remove WIP.

If you don't find anything wrong and don't want to then maybe should merge it

2022-12-11 19:55 UTC, zefhemel commented
Overall this works ok. The only issue I have is when the live preview kicks in. In its current behavior, this works strangely when adding spaces. I'm exegarating it in this video, but adding a space (even one) after `**Note**` is completely invisible and feels buggy:

https://user-images.githubusercontent.com/59073/206925584-3e52f795-027f-4a56-9d71-f3b494925760.mp4

How I would solve this myself is to simply be more conservative when to actually show the live preview icon. I would simply not do any of that magic if the cursor is _on the first line_ (the line with the admonition). That way you can always see all the markup (including spaces), and when you move to the second (non-header) line, the header renders as a preview. What do you think about that approach?

Alternatively somehow the space thing needs to be handled differently, now it feels a bit broken.

2022-12-11 20:00 UTC, zefhemel commented on web/styles/editor.scss
> +  .sb-admonition-title {
If it's empty, may as well remove?

2022-12-11 20:01 UTC, zefhemel commented on web/styles/editor.scss
> +  .sb-admonition {
It's better to move most of these styles (maybe simply all)? to `theme.scss` this will make it easier to make this themable down the line (not yet there, but preparing for it).

2022-12-11 20:07 UTC, zefhemel commented on web/cm_plugins/admonition.ts
> +                  iconRange.to,
```suggestion
 iconRange.from + 1,
```

Seems to work better for me? Puts the cursor in either `Note` or `Warning`

2022-12-11 22:48 UTC, christian-schulze commented
@zefhemel have addressed your other feedback.

Regarding the replacement of icon, have changed it to your first suggestion (within first line or not). Its a nifty feature but not essential. Will take another look at that later on.

2022-12-12 08:15 UTC, zefhemel commented
Great, this is nice. I'll merge it, we can tweak things later. Thanks!

2022-12-12 08:16 UTC, merged

2022-12-12 08:24 UTC, christian-schulze commented
> Great, this is nice. I'll merge it, we can tweak things later. Thanks!

Awesome thanks. You've got an interesting and useful project here, I'm happy to contribute more in future.