deno task build fixes for windows
silverbulletmd/silverbullet pull request #229
Opened 2022-12-22 22:20 UTC by kjk

Fix `deno task build` for Windows.

Windows doesn't support `.sh` files so replaced with direct usage in `deno.jsonc`.

Since we're no longer going via shell, the glob patterns are not expanded so modified `plugos-bundle.ts` to assume that if no files are given, we want to build everything and we glob ourselves.

Alternative: still pass glob pattern on cmd-line and glob internally (will be no-op if already globbed).

`build_plugs.sh` is no longer used but I left it in case you're using it from cmd-line.

Makes progress on #107

2022-12-24 11:54 UTC, zefhemel commented on plugos/bin/plugos-bundle.ts
> +    for (const file of expandGlobSync("plugs/*/*.plug.yaml")) {
I understand this works, but I think it’s quite ugly to hardcode this in a general-purpose command like plugos-bundle. In that case I’d rather have a `build_plugs.ts` specifically to build built-in plugs in the root dir (next to `build.ts`). This wouldn’t need to take any arguments, but just always build this set of plugs.

2022-12-24 11:55 UTC, zefhemel requested changes
See my comment. I understand this works, but it’s pretty hacky. Similar to the `deno task build` I’d then rather have a `build_plugs.ts` script that just builds the built-in plugs.

2022-12-25 22:34 UTC, kjk commented on plugos/bin/plugos-bundle.ts
> +    for (const file of expandGlobSync("plugs/*/*.plug.yaml")) {
created build_plugs.ts

2022-12-27 11:27 UTC, zefhemel commented
@kjk this is looking good and seems to work (on Mac at least 🤡 ) ready to merge?

2022-12-27 11:28 UTC, zefhemel approved these changes

2022-12-29 19:33 UTC, zefhemel commented
I’ll take your silence as a HELL YES 😉

2022-12-29 19:33 UTC, merged