add in new refactor file and extract to page command; #210
silverbulletmd/silverbullet pull request #286
Opened 2023-01-04 21:38 UTC by tristansokol

- `Refactor: Extract to new page` seems cumbersome, so I omitted the refactor. I'm not sure if the "category" is necessary for core plugins, but seems like a good idea for 3rd party. 
- mostly this is based on the existing plugs for renaming  (including the file overwrite protection) and text editing
- Happy to write some tests, but didn't see any infrastructure for it
- I don't know what `cmdDef.page` is doing, it seems like you can declare a argument in the yaml file, but I'm not sure how you would invoke it for page rename for example. Is that for use by other functions?

2023-01-04 21:42 UTC, tristansokol commented
ahh, with the github check I notice that the test are side by side, but mostly for the plugos. Let me know what you think and I can dig into deno testing

2023-01-04 22:04 UTC, zefhemel commented
Looking good, added a few comments. Adding tests is still cumbersome, I'd have to think how to make this easier. Let's leave it for now.

2023-01-04 22:05 UTC, zefhemel requested changes
Looking good, added a few comments. Adding tests is still cumbersome, I'd have to think how to make this easier. Let's leave it for now.

2023-01-04 22:05 UTC, zefhemel commented on plugs/core/refactor.ts
> +export async function extractToPage(cmdDef: any) {
Leave out this while cmdDef parameter, you don't need it. Also in the lines after. You'll want to ask for a page name anyway.

2023-01-04 22:05 UTC, zefhemel commented on plugs/core/refactor.ts
> +  await editor.replaceRange(selection.from, selection.to, "");
I'd imagine your wouldn't simply remove the text, but replace it with a `[[page reference]]` to the extracted page?

2023-01-04 22:05 UTC, zefhemel commented on plugs/core/refactor.ts
> +  await editor.navigate(newName, cursor, true);
The cursor position would be off here. Navigating to the new page makes sense, but I'd simply call `editor.navigate(newName)` here. That's it.

2023-01-05 01:09 UTC, tristansokol commented on plugs/core/refactor.ts
> +  await editor.replaceRange(selection.from, selection.to, "");
What do you think the typical use case for this is going to be? I'm not sure this is a command I'd use myself. 

Are you imagining pages that eventually become too big and need to be broken out, so this would be a shortcut to that? (not opposing your suggestion in anyway, I just don't have enough of a mental picture of how this would be used to have an opinion on what a good option would be)

2023-01-05 01:10 UTC, tristansokol commented on plugs/core/refactor.ts
> +export async function extractToPage(cmdDef: any) {
Could you briefly describe what the cmdDef does? Why does the renaming use it?

2023-01-05 01:11 UTC, tristansokol commented on plugs/core/refactor.ts
> +  await editor.navigate(newName, cursor, true);
```suggestion
  await editor.navigate(newName);
```

2023-01-05 01:11 UTC, tristansokol commented on plugs/core/core.plug.yaml
> +      page: ""
```suggestion
```

2023-01-05 07:54 UTC, zefhemel commented on plugs/core/refactor.ts
> +  await editor.replaceRange(selection.from, selection.to, "");
Exactly. I'm imagining (hence the name) "extract method" type of functionality: text getting too long, let's move this to a separate page and replace it with a link.

2023-01-05 07:56 UTC, zefhemel commented on plugs/core/refactor.ts
> +export async function extractToPage(cmdDef: any) {
Generally `cmdDef` gets passed whatever is in the command definition in the plug.yaml file, so its name, and any additional attributes put in there. The page rename is a unique case in that I call it directly from the UI when you update the page name in the top bar. This happens nowhere else in the code base. It's a shame you happened to find this case and copied 😉

2023-01-05 14:36 UTC, zefhemel commented
Code looks good. Tested this locally and seems to work great. Thanks!

2023-01-05 14:37 UTC, merged