Enable writing on the settings page from plugs
silverbulletmd/silverbullet pull request #45
Opened 2022-07-23 17:20 UTC by Willyfrog

The feature to read a settings is super nice, but wouldn't it be nice to allow plugs to write their own settings?

Also in this PR:
- Added an example use with the preview panel.
- Fixed a bug preventing having a setting to false

2022-07-23 17:20 UTC, Willyfrog commented on packages/plugs/lib/settings_page.ts
> -      if (allSettings[key]) {
this was driving me crazy for a bit as it was preventing any value to be falsy and using the default

2022-07-23 17:21 UTC, Willyfrog commented
if this is fixed, I'll use it for fixing https://github.com/Willyfrog/silverbullet-backlinks/issues/3

2022-07-23 17:28 UTC, Willyfrog commented on packages/plugs/markdown/markdown.plug.yaml
> +      name: "Swith Preview to other Sidebar"
Not super useful, but I used it as a test tool for the function and provides a simple example on how to use read and write settings function within the main repo.

2022-07-25 12:25 UTC, zefhemel requested changes

2022-07-25 12:25 UTC, zefhemel commented on packages/plugs/lib/settings_page.ts
> +    flashNotification("Creating a new SETTINGS page...", "info");
I wouldn't put UI stuff in something generally usable (from both client and server). It will break when using this API in a server context (there's no implementation of `flashNotification` there). Since you are not using `await` here it will silently fail (I think), but still.

2022-07-25 12:25 UTC, zefhemel commented on packages/plugs/lib/yaml_page.ts
> +  const newCode = `\`\`\`yaml\n${doc.toString()}\n\`\`\``;
I think we can roughly take two approaches to this `writeYamlPage` API:

1. "Let's surgically replace settings and leave everything as is" that means: let's keep the page text in place, comments in YAML, ideally, indentation etc. I'm not sure the yaml package we use is setup for this (preserving whitespace etc.) so this could be quite a challenge.
2. Let's just blow up the whole page and write it from scratch.

Since (1) is hard and not super important right now, I'd take the second approach. In which case you can get away without any fancy markdown parsing and rewriting, and go straight to the `writePage(pageName, newCode)` of this `newCode` variable (except maybe base it on the passed in template), because that's the core of it.

Or am I missing something?

2022-07-25 12:25 UTC, zefhemel commented on packages/plugs/markdown/markdown.plug.yaml
> +      name: "Swith Preview to other Sidebar"
Yeah it's a bit silly, but  also don't have a better sample use case right now.

2022-07-25 18:08 UTC, Willyfrog commented on packages/plugs/lib/yaml_page.ts
> +  const newCode = `\`\`\`yaml\n${doc.toString()}\n\`\`\``;
Yeah, I don't expect many people to write their own config, and also this will fail on a specific use case where the user documents the settings, as it is only considering one single yaml section. Eventually I'd love to support that, but it will probably make things much more complex so I'm ok with rewriting it.

I'd then also add a warning in the template that any unexpected node will be deleted.

2022-07-25 18:12 UTC, Willyfrog commented on packages/plugs/lib/settings_page.ts
> +    flashNotification("Creating a new SETTINGS page...", "info");
> there's no implementation of flashNotification there.

I still think it is important to let the user know that something has gone wrong. In this one is about creating a new settings page so user is not surprised and could be removed (although I prefer to let them know that there is a new page in their space). But a couple of lines later I use the same mechanism for error/success. if a setting fails to update I'd like the user to know.

is there a way to tell if this is client/server code? and once we know we are in the server, how do we tell the user about anything happening? (other than throwing errors)

2022-07-25 18:52 UTC, Willyfrog commented on packages/plugs/markdown/markdown.plug.yaml
> +      name: "Swith Preview to other Sidebar"
If we find a better example, we should remove this one :)

2022-07-25 18:55 UTC, Willyfrog commented on packages/plugs/lib/util.ts
> +  log(message); // we should end up sending the message to the user, users dont read logs.
not super happy with this, but at least it will prevent breaking.

2022-07-25 21:03 UTC, zefhemel commented on packages/plugs/lib/settings_page.ts
> +    flashNotification("Creating a new SETTINGS page...", "info");
There’s no mechanism right now to know if you’re being run on the client or server (although you can mark a function with `env: server` in the yaml file to make sure that it does only run in one env). What I usually do is throw an exception, these exceptions transfer across client-server boundaries. So in an API like settings_page, I’d simply throw an exception when things go wrong.

Then on the client side I can catch this exception, even if it occurs on the server when I invoke it remotely via `invokeFunction(“server”, …)` I can put a try-catch around it on the client side, and use a `flashNotification` in the catch-clause to show the error.

2022-07-25 21:04 UTC, zefhemel commented on packages/plugs/lib/util.ts
> +  log(message); // we should end up sending the message to the user, users dont read logs.
See my other comment, I’d just `throw Error(“FAIL”)` and catch it on the call site.

2022-07-25 21:05 UTC, zefhemel commented on packages/plugs/markdown/markdown.plug.yaml
> +      name: "Swith Preview to other Sidebar"
You can remove this and just use it in your backlinks plugin :)

2022-07-25 21:05 UTC, zefhemel commented on packages/plugs/lib/settings_page.ts
> -      if (allSettings[key]) {
You’re welcome 🤡

2022-07-25 21:14 UTC, zefhemel commented on packages/plugs/lib/settings_page.ts
> +    await notifyUser("Creating a new SETTINGS page...", "info");
Ok, now I see why you need the `notifyUser` thing, not just for errors but for "success" messages too. Alright. Ideally we would have a way to "push" notifications to the client, but this is not really possible right now so maybe switching between a console.log/error or flashNotification makes sense. Let's go with it for now.

2022-07-25 21:15 UTC, zefhemel approved these changes

2022-07-25 21:15 UTC, merged