Implement space-style
silverbulletmd/silverbullet pull request #796
Opened 2024-03-07 05:13 UTC by onespaceman

- add space-style blocks
- Also imports custom stylesheets from settings

For documentation, idk if this is now the official way to do user styles, with customStyles in settings remaining as a legacy option, or If you want to keep both official.

2024-03-07 18:02 UTC, zefhemel commented
This is very cool. I'll have a closer look at this later. Thanks for doing this!

2024-03-08 15:46 UTC, zefhemel requested changes

2024-03-08 15:46 UTC, zefhemel commented on web/client.ts
> +    const sortOrder = ["library", "user", "settings"];
Very clever that you thought about this, I like it.

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +  }
in `plug-api/lib/resolve.ts` there's a `cleanPageRef` function that removes the [[ and ]] if they're there (but also supports the format without [[ and ]]), it map be nice to `map` that function here, then the references lower down (e.g. line 43) get a bit cleaner too.

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +      console.log(codeOrigin);
This can probably go

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +      console.log(codeOrigin);
This can probably go

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +      console.log(codeOrigin);
This can probably go

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +    } else if (name.includes("Library")) {
maybe `.startsWith("Library/")`?

2024-03-08 15:46 UTC, zefhemel commented on plugs/index/style.ts
> +}>;
I just I realized I didn't do this for `space-script` yet either, but brownie points for adding this to the `plugs/index/builtins.ts` so you get nice auto complete for `space-style` and its attributes.

2024-03-08 15:47 UTC, zefhemel commented
As to documentation — feel free to include this part or not, happy to do it myself — but I think we can instantly consider `space-style` to be the successor to the customStyles thing, so I'd just remove all references to that option from the docs, and pretend we only have Space Styles now (with a `Space Style` page under `website/` documenting how to use it).

2024-03-08 21:45 UTC, onespaceman commented
All clear, captain.

2024-03-09 11:26 UTC, zefhemel commented
Tweaked a few things, but looking good. Thanks again for tackling this, merging!

2024-03-09 11:26 UTC, merged