Fix space on end of page name creates two pages, one shadowed #615
silverbulletmd/silverbullet pull request #817
Opened 2024-03-17 17:25 UTC by fflorent

## Context

Fixes #615.

## Proposed solution

1. Disallow PUT on filename with filenames surrounded with spaces;
2. If the filename provided on GET is surrounded by spaces, redirect to its trimmed version;
3. In case of required authentication, return a 401 (UNAUTHORIZED) + redirect;

## Other

If you want me to create tests, I would like to know if there already exists files places I can put them in.

2024-03-18 19:10 UTC, zefhemel requested changes

2024-03-18 19:10 UTC, zefhemel commented on common/spaces/http_space_primitives.ts
> +          location.href = result.url;
Previously it would show an alert in this case, any particular reason why it shouldn't anymore?

2024-03-18 19:10 UTC, zefhemel commented on server/http_server.ts
> +        const mdExt = ".md";
If you introduce constants like this, I'd prefer them at the top level (top of the file, next to `authenticationExpirySeconds`) for instance.

2024-03-18 20:23 UTC, fflorent commented on common/spaces/http_space_primitives.ts
> +          location.href = result.url;
The alert still appears when the reason of the redirection is a `401 - Authentication Required` (line 42) and the server code has been adapted below (in `server/http_server.ts:491`).

2024-03-18 20:23 UTC, fflorent commented on server/http_server.ts
> +        const mdExt = ".md";
Done

2024-03-22 20:19 UTC, fflorent commented on common/spaces/http_space_primitives.ts
> +          location.href = result.url;
@zefhemel Does this answer your question? Or you are still worried about that change?

2024-03-23 19:02 UTC, zefhemel commented
Sorry for the delay, this looks good. Thanks!

2024-03-23 19:02 UTC, merged