Index []() style links
silverbulletmd/silverbullet pull request #827
Opened 2024-03-23 00:36 UTC by onespaceman

- []() style links
  - No longer opens in new window if link is local
  - Now indexed if local
  - Page completion
  - Changed on rename and refactor
    - Refactor now uses link position from the index to change references
- New query for linked attachments

2024-03-23 18:34 UTC, zefhemel commented
This is very nice! Let me have a closer look at this and do some testing.

2024-03-24 13:55 UTC, zefhemel commented
I've noticed that linking to other pages with the `[hello](somepage)` only works for pages linked to without spaces, so `[hello](some page)` doesn't work, because the underlying markdown parser doesn't accept it. I was thinking of different options, but probably the best one would be to patch the markdown parser somehow. Alternatively we just don't support page links with spaces, or support them, but URL encoded (e.g. `other%20page`) but that doesn't seem great either.

2024-03-24 13:57 UTC, zefhemel commented
Another question is: should attachment links be tagged with `attachment` or e.g. `attachmentlink` or `attachmentLink`. I think it would be useful to reserve `attachment` (the files themselves) and index them with their own attributes (such as file size, lastModified, contentType etc.)

2024-03-24 13:58 UTC, zefhemel requested changes

2024-03-24 13:58 UTC, zefhemel commented on plugs/index/refactor.ts
> +  const backLinksByPage = Object.groupBy(backLinks, (o) => o.page);
Even though in all current versions of browsers seem to support Object.groupBy, it wasn't even a few months at go in iOS 17.3 and before. Could you replace this with something more compatible?

https://caniuse.com/mdn-javascript_builtins_object_groupby

2024-03-24 20:26 UTC, onespaceman commented
> I've noticed that linking to other pages with the `[hello](somepage)` only works for pages linked to without spaces, so `[hello](some page)` doesn't work, because the underlying markdown parser doesn't accept it. I was thinking of different options, but probably the best one would be to patch the markdown parser somehow. Alternatively we just don't support page links with spaces, or support them, but URL encoded (e.g. `other%20page`) but that doesn't seem great either.

Yeah, apparently the [correct way](https://spec.commonmark.org/0.31.2/#link-destination) to enclose the link with <> if it has whitespaces. It doesn't work right now, but I could add it and call it a day. I'm not a fan, but if the spec says this is how it must be, who am I to argue?

2024-03-24 21:20 UTC, onespaceman commented
> Another question is: should attachment links be tagged with `attachment` or e.g. `attachmentlink` or `attachmentLink`. I think it would be useful to reserve `attachment` (the files themselves) and index them with their own attributes (such as file size, lastModified, contentType etc.)

Good point. another option is to combine with regular LinkObjects as a union

```
type LinkObject = ObjectValue<{
  // Page Link
  // The page the link points to
  toPage: string;
  // The page the link occurs in
  page: string;
  pos: number;
  snippet: string;
  alias?: string;
  asTemplate: boolean;
  toFile?: never;
} | {
  // Attachment Link
  // The file the link points to
  toFile: string;
  // The page the link occurs in
  page: string;
  pos: number;
  snippet: string;
  toPage?: never;
  alias?: never;
  asTemplate?: never;
}>;
```

What do you think?

2024-03-26 19:51 UTC, zefhemel commented
> > I've noticed that linking to other pages with the `[hello](somepage)` only works for pages linked to without spaces, so `[hello](some page)` doesn't work, because the underlying markdown parser doesn't accept it. I was thinking of different options, but probably the best one would be to patch the markdown parser somehow. Alternatively we just don't support page links with spaces, or support them, but URL encoded (e.g. `other%20page`) but that doesn't seem great either.
> 
> Yeah, apparently the [correct way](https://spec.commonmark.org/0.31.2/#link-destination) to enclose the link with <> if it has whitespaces. It doesn't work right now, but I could add it and call it a day. I'm not a fan, but if the spec says this is how it must be, who am I to argue?

Really? First time I heard of that notation. Markdown is a new surprise every day 😆

2024-03-26 19:53 UTC, zefhemel commented
> > Another question is: should attachment links be tagged with `attachment` or e.g. `attachmentlink` or `attachmentLink`. I think it would be useful to reserve `attachment` (the files themselves) and index them with their own attributes (such as file size, lastModified, contentType etc.)
> 
> Good point. another option is to combine with regular LinkObjects as a union
> 
> ```
> type LinkObject = ObjectValue<{
>   // Page Link
>   // The page the link points to
>   toPage: string;
>   // The page the link occurs in
>   page: string;
>   pos: number;
>   snippet: string;
>   alias?: string;
>   asTemplate: boolean;
>   toFile?: never;
> } | {
>   // Attachment Link
>   // The file the link points to
>   toFile: string;
>   // The page the link occurs in
>   page: string;
>   pos: number;
>   snippet: string;
>   toPage?: never;
>   alias?: never;
>   asTemplate?: never;
> }>;
> ```
> 
> What do you think?

Actually yeah, that makes sense, let's do that. I suppose you can easily filter one or the other by filtering on either `toPage` or `toFile`.

2024-03-27 19:46 UTC, onespaceman commented
While I'm doing this I'm also adding in updating attachment links on rename/refactor (fixes #733)
questions:
1. Should attachment links be the same as wikilinks where every link assumes it's from the base folder, or should it refer to the note's folder like it is now? ie Page is `[[subfolder/Page]]`. image.png is inside subfolder. Link right now -> `[](image.png)`. Should it be `[](subfolder/image.png)`?
2. Should I add support for attachment wikilinks? -> ![[image.png]], Should it be the default?
3. When a Page is moved where do the attachments go?
  - Option 1: Only update the links, Keep the attachment where it is.
  - Option 2: If the attachment is in the same folder as the page, and is only linked to on that page, move it with the page. Otherwise do option 1

2024-04-04 18:41 UTC, zefhemel commented
1. Right, so the semantics of links and image links should be that they’re relative, to be consistent with default markdown behavior. 
2. I think that would be great actually. And making that the default drag & drop etc. behavior… good question. Maybe?

4. Option 2 would be the nicest I’d say

2024-05-10 18:14 UTC, onespaceman commented
Ok, this turned out to be pretty big, so I did a hard reset and tried to break it into digestible commits.
I tried to be as thorough as possible with testing because it involves editing/moving pages so I don't want to mess up anyone's files.

Here is a basic space setup I used for testing how renaming works with rewriting links
https://gist.github.com/onespaceman/da4eaed2e6808e7342840c9f680ce84d
I also used a copy of my personal vault to rename and prefix rename everything and anything, it seems to work perfectly, but please take your time to test it out yourself.

Also I had a really weird bug with importing regex constants.
https://github.com/onespaceman/silverbullet/blob/b17a2d0d468034d5434a88c7102639bf0a4da3d2/web/cm_plugins/inline_image.ts#L67
https://github.com/onespaceman/silverbullet/blob/b17a2d0d468034d5434a88c7102639bf0a4da3d2/web/cm_plugins/inline_image.ts#L70
When using the imported regex, the inline images would only show up every other image, and the visible images would disappear and the not shown images would appear on any refresh, such as moving the cursor or typing a character. This doesn't happen when I would replace the constant by pasting the same regex directly. Idk what is going on there.

2024-05-14 09:06 UTC, zefhemel commented
Ok let me give this a try. We clearly need an end-to-end style testing framework for SB for things like this 😆

2024-05-14 09:11 UTC, zefhemel commented on plug-api/lib/resolve.ts
> +export function absoluteToRelativePath(page: string, linkTo: string) {
Is this function used anywhere? I don't see references to it.

2024-05-14 09:16 UTC, zefhemel commented on plugs/index/refactor.ts
> +  await system.invokeFunction("index.reindexSpace");
Do you really think this is necessary? On large spaces, this may take minutes.

2024-05-14 09:17 UTC, zefhemel commented on plugs/index/refactor.ts
> +  await system.invokeFunction("index.reindexSpace");
If I'm reading this code right, this function is even used when renaming a single page, right? That would not be scalable TBH. A full reindex for every page rename would take too much time on any reasonably sized space.

2024-05-14 09:21 UTC, zefhemel commented on plugs/index/refactor.ts
> +  await system.invokeFunction("index.reindexSpace");
Confirmed from manual testing, even for a single page rename it reindexes. We can't really do that...

2024-05-14 09:28 UTC, zefhemel commented
Issue: 

When auto completing an image URL with a space in the name, it expands to a syntax with `<`, e.g.
```
![bla](</zefzefzef 3/americans-europeans-2.jpeg>)
```

which then breaks in the live preview (it shows the image as a broken link). I think this may just not be valid markdown at all, and may have to resort to a URL encoded URL?

2024-05-14 09:39 UTC, zefhemel commented on web/hooks/slash_command.ts
> +    // No slash commands in comment blocks (queries and such) or links
Yes!

2024-05-14 09:43 UTC, zefhemel commented on plugs/index/attachment.ts
> +export async function reindexAttachments() {
page indexing happens through a MQ, maybe something to also consider for attachments? Not a must have, but a nice to have I'd say (may be valuable especially once people have a ton of attachments).

2024-05-14 09:44 UTC, zefhemel commented
Overall, once again: thanks for making this effort. It's looking really good, and we now will have code complete for attachments, which I'm pretty sure was missing until now. At some point SB may actually become decent for stuff that involves not primarily text files 😆

2024-05-14 17:42 UTC, onespaceman commented on plug-api/lib/resolve.ts
> +export function absoluteToRelativePath(page: string, linkTo: string) {
Yes, in refactor.ts for rewriting relative links.

2024-05-14 17:48 UTC, onespaceman commented on plugs/index/refactor.ts
> +  await system.invokeFunction("index.reindexSpace");
Yeah, that should be deleted. I was getting errors, so I added that, but later realized I was just overwriting my space with an old database file.

2024-05-15 00:18 UTC, onespaceman commented on plugs/index/attachment.ts
> +export async function reindexAttachments() {
It already does that. This is for reindexing the whole space

2024-05-15 00:25 UTC, onespaceman commented on plugs/index/attachment.ts
> +export async function reindexAttachments() {
nevermind. it does not. Queue seemed unnecessary to me since indexing doesn't process attachments like it does pages, but for large spaces it would be nice.

2024-05-16 17:51 UTC, onespaceman commented
I think that covers those issues. let me know if anything else needs changing

2024-05-19 08:56 UTC, zefhemel commented
This looks almost good to go, just found one issue:

You auto complete a page with `[[something` it now completes attachment files too, not just pages. Now the question is actually: while a regression, is this perhaps desired? That way you can link to attachments without using `[]()` style links 🤔  Did you do this on purpose?

2024-05-19 09:00 UTC, zefhemel commented
Ok, it is inconsistent with the `![[image.png]]` syntax that is also supported now (I even forgot we have this, or did you add it here?) at least when completing `![[image.png` I'd expect _only_ attachments (perhaps even just images) to be completed, not pages as well.

So honest, I'd prefer to keep using `[[page]]` just for pages, and `![[image.png]]` for attached images.

2024-05-19 09:04 UTC, zefhemel commented
Ok I think you indeed added the `![[image.png]]` in this PR as well correct? That's cool, but then I found an additional bug:

* When you have a page in a folder and drag & drop an image into, it translates this to `![[image.png]]` which breaks, because it assumes an absolute path (so should include the current folder), so the folder name should be prepended to it. This is different than the previous behavior of using the `![]()` syntax, where paths are relative.

2024-05-20 21:54 UTC, onespaceman commented
That should fix the upload path. I'll fix merge conflicts later.

2024-05-20 22:04 UTC, onespaceman commented
Embeding page links is the next thing I'm working on. So if you don't mind it doing nothing for a little bit, I'll just leave it as is.
I was just going to make it a shortcut for a live template.
Making it an editable transclosure is probably a future pr (idk if I even have the knowledge to do it)

2024-05-21 04:16 UTC, zefhemel commented
Sure, that sounds great. Making the tansclosure editable is not a priority imo. Using it as a live template is also what I'd go for.

2024-05-22 16:35 UTC, onespaceman commented
#833 is unfortunately a major pain for refactoring and for autofilling links.
Do you mind if I rewrite it to use `![alt text | resolution](filename.png)` format suggested in #493 . It would also match the format for wikilinks `![[image.png|resolution]]`

2024-05-23 19:10 UTC, zefhemel commented
Personally I have no strong preference. I don't know to what extent this is any way standardized. Incompatibility with other tools (maybe GitHub not sure of it even supports it) would be by only concern.

2024-05-24 22:40 UTC, onespaceman commented
It's not standardized at all. Obsidian uses the format I suggested, most of the rest, including github use html embeds.
`<img src="image.png" width="200" height="100">`

This way is probably better because links will still work as normal

2024-05-25 09:02 UTC, zefhemel commented
I'm perfectly fine with changing it then

2024-05-25 21:42 UTC, onespaceman commented
there. should be ready

2024-05-27 17:17 UTC, zefhemel commented
Ok this looks good and seems to work as expected

Two questions remain:

* Auto completing `![[` shows also pages, is this in preparation for the "embedding" that you'll implement later? If so, then maybe it's ok to leave it like this for a bit
* Auto completing `[[` also auto completes attachments, is this intended? I can see arguments for it

2024-05-27 17:56 UTC, onespaceman commented
yes to both.
For 2, I'm thinking that wikilinks = local files

2024-05-27 18:33 UTC, zefhemel commented
Alright. Let's do this!

2024-05-27 18:33 UTC, merged

2024-05-27 18:34 UTC, zefhemel commented
Thanks again. This is awesome stuff.