Support size for images
silverbulletmd/silverbullet pull request #833
Opened 2024-03-31 15:50 UTC by fflorent

Fixes #493

2024-04-04 18:43 UTC, zefhemel commented
Thanks for this, I’ll have a closer look soon. Bit busy, but you’re not forgotten :-)

2024-04-04 18:44 UTC, zefhemel commented
Is it ready to look at? It’s marked as draft.

2024-04-07 14:07 UTC, fflorent commented
> Is it ready to look at? It’s marked as draft.

Sure! Also it is a working version. I just have doubts:
  - as it is not standard markdown, I have not much opinion about the extension we should implement, though I wonder if there would not be some alternative we could implement and that could be a better fit (like a syntax that could be extended to allow more features, like [Kramdown does](https://kramdown.gettalong.org/syntax.html#images));
  - I am not sure when markdown_reader.ts is executed, is it related to the federation feature?

2024-04-18 08:56 UTC, zefhemel commented
Sorry for the delay on this. To answer your question on where markdown_render is used: this is used in a few places:

* Markdown preview (Ctrl-p)
* Markdown table rendering (when the cursor is not in a markdown table)
* Any markdown widget, this includes live templates and live queries

On the latter, an easy way to test this:

~~~
```template
Put your ![image](....) here
```
~~~

In your implementation, you don't currently inject any width and height during markdown_rendering, correct? So this would be something to add. Other than that this looks great!

2024-05-08 14:17 UTC, fflorent commented on plugs/markdown/markdown_render.ts
> +        dimensionsToParse.match(/(\d*)(%)?x(\d*)(%)?/) ?? [];
By chance, do you have any idea where this piece of code could be factorized? It's just a copy-paste from `InlineImageWidget#getDimensions()`

2024-05-14 07:29 UTC, zefhemel requested changes
One very minor request

2024-05-14 07:29 UTC, zefhemel commented on common/markdown_parser/parser.ts
> +export const imageWithSizeRegex =
Since regexes are hard to read for regular people, it would be very helpful to add a comment with 1-2 examples that match this regex here I think

2024-05-14 07:29 UTC, zefhemel commented on plugs/markdown/markdown_render.ts
> +function preprocess(t: ParseTree) {
Thanks for removing this, I've been thinking to remove it every time I open this file but thought "nah, maybe we'll need it later". KILL ALL THE CODE :D

2024-05-14 07:29 UTC, zefhemel commented on plugs/markdown/markdown_render.ts
> +        dimensionsToParse.match(/(\d*)(%)?x(\d*)(%)?/) ?? [];
Honestly in this case I'd stick with the duplication. I was thinking of moving it in with the parser code, but that way you pull in the entire markdown parser into a plug which isn't great.

2024-05-14 20:50 UTC, fflorent commented on common/markdown_parser/parser.ts
> +export const imageWithSizeRegex =
Done!

2024-05-19 09:05 UTC, zefhemel commented
Awesome, thanks a lot!

2024-05-19 09:05 UTC, merged