Initial attempt to fix #560
silverbulletmd/silverbullet pull request #905
Opened 2024-06-27 19:59 UTC by deepkn

Enables decorations for user specified tags - currently supporting only a single decoration - a 'prefix' to be added to the page name. Prefix is handled in the top bar title, page navigator as well as links.

Since visually identifying my defined object types was somewhat important for me, I took a stab at #560 - Quite unfamiliar with typescript and in general PWAs - so there could be a lot that can be improved and even better ways to do this. Open to suggestions.

TODO: Handle this in queries as well, at least when rendered via templates - but I'm wondering if that could be achieved better by simply extracting out the prefix as an attribute and using that (leaving it to the user)

2024-07-02 13:30 UTC, zefhemel commented
This looks promising. Definitely a good starting point to a more elaborate implementation. I'll have a closer look soon!

2024-07-03 05:49 UTC, zefhemel commented
A few issues I've found:

* I'm not sure the prefix should actually become part of the page name in the top bar. I think it should be put in front of the editor component somehow so you cannot edit it out. Right now, you can simply remove the prefix there, which is a bit weird.
* The prefix is only added in the top bar page title when you navigate from another page to it, not when the page is loaded refresh (reload the page and you'll see what I mean)
* The prefix is only rendered for wiki links when they're out of the selection scope. I think may be ok, although it would be slightly nicer if it would also be there in the code complete as well as when the cursor is inside the link:

![CleanShot 2024-07-03 at 07 48 59](https://github.com/silverbulletmd/silverbullet/assets/59073/c2ae70cd-5388-4cbd-9f9d-501f34911498)

Some of these issues may be harder to get done. If you get stuck or you'd like me to take over let me know. This is a good start, and this is definitely something I'd like to get in soon, so happy to help!

2024-07-04 07:10 UTC, deepkn commented
Thanks Zef. Happy to take another shot at it - after all I'm loving SilverBullet a bit too much :)
1. That makes sense - I'm guessing that would have to go as another component for prefix before the MiniEditor; do correct me if I'm completely off here.
2. I did see this happening last day - I mostly never leave keyboard while navigating(one of the things I love about sb) so that missed my eye. I think I know what's happening there - infact I think the very first commit would not have had this problem. Let me think of a cleaner fix.
3. Sounds like a little bit more trickier to do - atleast based on what I have explored so far, so any pointers welcome. But I'll still take a shot at it in the coming days.

2024-07-06 16:35 UTC, zefhemel commented
Let me know when I can have another look!

2024-07-06 18:16 UTC, deepkn commented
Hey Zef, I think you can take another look. 1) and 2) from before must be fixed now and for 3) enabling the prefix in code complete turned out to be easier than I thought since codemirror autocomplete allows for a displayName override. What the latest patch doesn't have is the display of prefix when the cursor is inside the link.

2024-07-07 10:19 UTC, zefhemel commented
This is getting close! However I see some issues still especially on first load. See this GIF that I kick off with a reload. I hope that my mouse gesturing makes clear what I'm pointing at 😉 

![CleanShot 2024-07-07 at 12 17 55](https://github.com/silverbulletmd/silverbullet/assets/59073/f842415a-2398-4adb-b8ce-3fdb3fd114e4)

2024-07-07 19:24 UTC, deepkn-ntnx commented
Ah... dang - I should've seen that coming.!! Because reload clears everything and we need to wait for index to be built to get the tags to which the corresponding prefix was to be applied, I was updating that when the page list update is done, which happens async in the init sequence. It was not very apparent for me since I have a smaller number of pages currently - but I can guess what's happening on your end :) Since we do not want to block the app load on this, I guess this will always be async and there will be some delay - since the title is readily available - but the prefix is not until index is done atleast for the page in question. Few options that we can try from the top of my head:

1. await and query for the current page and update, instead of the entire pages to be indexed - but in the worst case, it'll look the same.
2. use browser's cache to cache current decorators for the page - but hard reload would see the same thing happening.
3. there is a neat little way around this which I'm obviously not seeing - I'm too new to this ;)

Would like your inputs on this one.

On displaying the prefix when cursor is inside a link - I have a way to do that, but I'm wondering if we'd end up with the same weirdness that you found in the topbar - since it's in the editor, that'll remain editable and the user could just remove it from the link if he chooses to - and it may come back to life if he moves the cursor out and back in again. I don't think we can make that non-editable within the editor component. What do you think?

2024-07-07 19:25 UTC, deepkn commented
Ah... dang - I should've seen that coming.!! Because reload clears everything and we need to wait for index to be built to get the tags to which the corresponding prefix was to be applied, I was updating that when the page list update is done, which happens async in the init sequence. It was not very apparent for me since I have a smaller number of pages currently - but I can guess what's happening on your end :) Since we do not want to block the app load on this, I guess this will always be async and there will be some delay - since the title is readily available - but the prefix is not until index is done atleast for the page in question. Few options that we can try from the top of my head:

1. await and query for the current page and update, instead of the entire pages to be indexed - but in the worst case, it'll look the same.
2. use browser's cache to cache current decorators for the page - but hard reload would see the same thing happening.
3. there is a neat little way around this which I'm obviously not seeing - I'm too new to this ;)

Would like your inputs on this one.

On displaying the prefix when cursor is inside a link - I have a way to do that, but I'm wondering if we'd end up with the same weirdness that you found in the topbar - since it's in the editor, that'll remain editable and the user could just remove it from the link if he chooses to - and it may come back to life if he moves the cursor out and back in again. I don't think we can make that non-editable within the editor component. What do you think?

2024-07-08 18:32 UTC, zefhemel requested changes

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +  updateDecoratorConfig();
Maybe `await` this so that you can be sure `decorations` will have a value from the first invocation (and you catch errors, which otherwise would go into the void).

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +      const decor = decorations?.filter(d => pageMeta.tags?.some((t: any) => d.tag === t));
`docorations` will always have a value, right? So no need for the `?` after it?

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +      if (decor === undefined || decor.length == 0) {
And without the `?` from my previous comment, this can just become a `.length` check only probably.

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +            displayLabel: `${decoratedName}`,
How about just `displayLabel: decoratedName,`

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +              displayLabel: `${decoratedName}`,
Same as above.

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +          displayLabel: `${decoratedName}`,
Same again

2024-07-08 18:32 UTC, zefhemel commented on plugs/editor/complete.ts
> +      const decor = decorations?.filter(d => pageMeta.tags?.some((t: any) => d.tag === t));
And maybe use `.find` instead of `.filter`?

2024-07-08 18:32 UTC, zefhemel commented on plugs/markdown/markdown_render.ts
> +          const pageMeta = allPages.filter(p => t.attrs!["data-ref"]!.startsWith(p.name));
Maybe `.find` instead of `.filter`?

2024-07-08 18:32 UTC, zefhemel commented on web/cm_plugins/wiki_link.ts
> +        const pageMeta = client.ui.viewState.allPages.filter(p => p.name == url);
-> `.find` again

2024-07-08 18:32 UTC, zefhemel commented on web/reducer.ts
> +      const pageMeta = state.allPages.filter(p => p.name == action.meta.name);
`.find`

2024-07-08 18:32 UTC, zefhemel commented on web/reducer.ts
> +      const decor = state.settings.decorations?.filter(d => pageMeta[0]?.tags?.some(t => d.tag === t));
`.find`

2024-07-08 18:32 UTC, zefhemel commented on web/reducer.ts
> +        const decor = state.settings.decorations?.filter(d => pageMeta.tags?.some((t: any) => d.tag === t));
`.find`

2024-07-08 18:40 UTC, zefhemel commented
In addition to the comments before, another ask:

In the near future I'd be interested in adding additional decorator things to pages, including e.g. colors or background colors (in addition to name prefixes). Therefore it seems to be useful to not specifically attach the `.namePrefix` to `PageMeta`, but just add `decoration` property (of type `Decoration`) to it, so that other properties (in addition to `prefix`) can be read from it in the future?

2024-07-08 18:46 UTC, zefhemel commented
The delayed showing of prefix in the top bar is acceptable I think, hard to fix that in a way that wouldn't slow a lot of things down. Not showing the emoji in the "cursor is in the link" state is actually desirable now that I think about it, it's consistent with "this shows what the ACTUAL underlying markdown is" philosophy, so that should stay that way.

However, not showing the prefix in the page wiki link until you move your cursor around is less idea. Basically what needs to happen is that whenever a `update-page-list` reducer is action is triggered, the editor updates (rerenders). I think you can do this with an empty `editorView.dispatch({})`. Have a look if you can figure that out. If not, address the issues in my comments and I'll merge it and try to fix that little issue myself.

Awesome work so far! Very eager to use this and take it further.

2024-07-08 18:47 UTC, zefhemel commented on plugs/editor/complete.ts
> +      if (decor === undefined || decor.length == 0) {
And when switching to `.find` you can just check of not undefined I suppose.

2024-07-11 20:15 UTC, deepkn commented
> In addition to the comments before, another ask:
> 
> In the near future I'd be interested in adding additional decorator things to pages, including e.g. colors or background colors (in addition to name prefixes). Therefore it seems to be useful to not specifically attach the `.namePrefix` to `PageMeta`, but just add the full blown `decoration` property (of type `Decoration`) to it, so that other properties (in addition to `prefix`) can be read from it in the future. Would that be ok?

This makes sense - the only question I had here is the decorations could be, atleast in theory, a merge of different decorators defined for different tags applied to a page. Does it make sense to keep it merged per page? Maybe take a look at the latest update and see if that makes sense to you?

2024-07-12 16:10 UTC, zefhemel commented
I think it’s ok as is. If you can merge with current `main` and resolve the conflict I’ll give it another test and we can merge it and iterate from there. Thanks for this, looking forward to try and add to this!

2024-07-13 08:56 UTC, closed without merging