Per-tag page styling
silverbulletmd/silverbullet pull request #945
Opened 2024-07-15 16:22 UTC by onespaceman

2024-07-15 17:18 UTC, zefhemel requested changes
Nice feature! I'd also be interested in something like this for https://silverbullet.md/Page%20Decorations

That's separate of course, or maybe not?

2024-07-15 17:18 UTC, zefhemel commented on web/client.ts
> +      if (enrichedMeta.itags) {
I'm thinking in what scenario this is not set and if that's the case if the attribute shouldn't be cleared?

2024-07-15 17:18 UTC, zefhemel commented on web/client.ts
> +        editorView.contentDOM.setAttribute("tags", pageTags);
For form and attribute pollution reasons should this attribute be called `data-tags`?

2024-07-16 06:42 UTC, onespaceman commented
Moved the attributes to the body tag, with data- prefix.
Now all metadata properties are added, but I'm not sure if the some like the contenttype, dates, or perms are useful. Should I filter them out?

> I'd also be interested in something like this for https://silverbullet.md/Page%20Decorations

I'm not sure what you're asking for here?

2024-07-16 18:06 UTC, onespaceman commented
Ok on a reread, I think that, instead of injecting the html for the prefix, you want to just attach a class to the links, and let people do whatever with it with space styles instead. Is that correct?

2024-07-17 19:41 UTC, onespaceman commented
Honestly, this is a pretty powerful feature. Allow any property instead of just a class, rebrand it as an autotagger, and now add page tags and whatever other metadata to page through a query.

Then attach the meta properties as attributes to the html and style as you please through space-styles

```
*[myProperty="value"] {
  color: #F00;
}
```

Could even do the same with the prefixes.

```
*[pagePrefix="tree"]::before {
  content: "🎄 ";
}

2024-07-22 15:38 UTC, zefhemel commented on web/client.ts
> +    for (const p in meta) {
Should this `p` not be somehow normalized before injecting it into the DOM? Potentially there could be weird characters in there, spaces, maybe other things?

2024-07-24 05:53 UTC, onespaceman commented
Check what I have so far if this is what you wanted.

an example snippet for page decorations based on itag:
```
/* add a prefix /*
body[data-itags~="test"] #sb-current-page .cm-line::before
a[data-itags~="test"]::before,
.sb-option[data-itags~="test"] .sb-name::before {
  content: "✨ ";
}

/* color it purple */
body[data-itags~="test"] #sb-current-page .cm-line,
a[data-itags~="test"],
.sb-option[data-itags~="test"] .sb-name {
  color: purple;
}
```

2024-07-24 08:08 UTC, zefhemel requested changes

2024-07-24 08:08 UTC, zefhemel commented on lib/web.ts
> +  attributes?: { [key: string]: string };
Minor, but I tend to use `Record<string, string>` generally

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +  attributes?: { [key: string]: string };
Same as above

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +    for (const a in this.options.attributes) {
I get nervous seeing this pattern in modern JS. I prefer the safer `for(const [attr, val] of Object.entries(this.options.attributes))`

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +  for (let m in meta) {
Same as above, I prefer Object.entries()

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +  let attributes: any = {};
Why not `Record<string, string>`?

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +    if (["created", "lastmodified", "perm"].includes(m.toLowerCase())) {
I don't think you need to lowercase this? I think these will always be capitalized consistently? `created`, `lastModified`, `perm` no?

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/util.ts
> +    if (["created", "lastmodified", "perm"].includes(m.toLowerCase())) {
And maybe you want to style based on `perm` 🤷🏻

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/wiki_link.ts
> -          ((pageMeta?.pageDecoration?.prefix ?? "") + cleanLinkText);
This seems to break `prefix` decorations, why did you remove this?

2024-07-24 08:08 UTC, zefhemel commented on web/editor_state.ts
> +            if (completion.metaData) {
So this would allow to style auto complete as well? If so, an example of this would be helpful in the docs.

2024-07-24 08:08 UTC, zefhemel commented on web/cm_plugins/wiki_link.ts
> +        console.log(attributes);
Probably want to remove this one

2024-07-28 21:13 UTC, onespaceman commented on web/cm_plugins/wiki_link.ts
> -          ((pageMeta?.pageDecoration?.prefix ?? "") + cleanLinkText);
This replaces pagedecorations no? see comment below for reasoning.

2024-07-28 21:42 UTC, onespaceman commented
Just to go over what I have in mind:
1. Autotagger - 
Apply any arbitrary tag in settings instead of just limited to prefix.
Example:
```
autotag:
- where "tags= 'testTag'"
tags: "additionalTag"
iLikeKeys: "And also values"
hidden: true
```

2. Add a hidden property to pageMeta so that it can be hidden on a page-to-page basis or through autotagger instead of relying on prefix.

3. Attach pagemeta to wherever page names and page links appear, so that it can be styled with space-styles as shown [here](https://github.com/silverbulletmd/silverbullet/pull/945#issuecomment-2246960131). More flexible by allowing to style colors, background, font, prefix etc. at the cost of a somewhat ugly and harder to understand css snippet.
Or I could keep the prefix option, generate the css, and append it when building space-styles.

2024-07-29 07:34 UTC, zefhemel commented
> Just to go over what I have in mind:
> 
> 1. Autotagger -
>    Apply any arbitrary tag in settings instead of just limited to prefix.
>    Example:
> 
> ```
> autotag:
> - where "tags= 'testTag'"
> tags: "additionalTag"
> iLikeKeys: "And also values"
> hidden: true
> ```

So I was thinking along similar lines when I wrapped up the initial version of pageDecorations. My thinking was: what if we would add a generic mechanism to add attributes dynamically to _any_ object (selected based on a `where` clause like pageDecorations and other things work now). This would be a way to dynamically add pageDecorations onto pages, but could be used in other ways too. You could create dynamic attributes on tasks, you could use these attributes in queries etc.

For instance, you could then implement page decorations like this:

```yaml
decorators:
- where: 'tags = "person"'
  attributes:
     pageDecoration.prefix: "🥸 "
```

Or an even more out-there solution would be to allow Expressions as values so they can be dynamically computed:

```yaml
decorators:
- where: 'tags = "person"'
  attributes:
     pageDecoration.prefx: '"🥸 "' # Just a literal string
     fullName: "firstName + ' ' + lastName" # Compute based on other attributes, you could even call functions here
```

This would give all #person tagged objects a pageDecoration and fullName automatically. This would need to be implemented at the DataStore level.

In the end I didn't go for it because I feared that:

1. It would be too expensive, e.g. the way queries work is basically through a table scan where every item is evaluated against the `where` clause. This would add more complexity to that: as in, it would also have to create an "enriched" version of the item with all these dynamic attributes added and then run the filter against that. This seemed potentially expensive.
2. It adds complexity. Before you could just see: these are the attributes of this page, it's obvious because some are built in (like lastModified), others I defined in the front matter. That's it. No surprises. Adding dynamic attributes based on selectors could make this a whole lot more complicated (especially if people accidentally do things like applying them to _all_ objects, e.g. when they'd just say `where true` 🤯 )

But I'm open to be challenged on this. And as I'm writing this, I'm tempted to try it. I think this can be done, and it would be a very powerful mechanism that can be leveraged for various use cases, not just page decorations. But it's also one of those "with great power comes great responsibility" type of things.

> 2. Add a hidden property to pageMeta so that it can be hidden on a page-to-page basis or through autotagger instead of relying on prefix.

I'm not sure I follow this one.

> 3. Attach pagemeta to wherever page names and page links appear, so that it can be styled with space-styles as shown [here](https://github.com/silverbulletmd/silverbullet/pull/945#issuecomment-2246960131). More flexible by allowing to style colors, background, font, prefix etc. at the cost of a somewhat ugly and harder to understand css snippet.
>    Or I could keep the prefix option, generate the css, and append it when building space-styles. That way a simple prefix option is available in settings, with more advanced styling through space-styles.

I think the prefix use case is going to be the most common thing, so I'd prefer to keep that easy to do, as it is. I also still like my suggestion to add an explicit `pageClass` attribute to `pageDecoration` that would then be attached to the body to make targeting CSS styles easier. I'm ok with also attaching other page attributes to the body as `data` attributes, but for me that's less essential because you can achieve the same thing with `where` targeted decorations.

2024-07-29 12:59 UTC, zefhemel commented
FYI: I'm working on (1) as I proposed after all. Performance impact doesn't seem bad, hang tight :)

2024-07-29 15:05 UTC, onespaceman commented
> FYI: I'm working on (1) as I proposed after all. Performance impact doesn't seem bad, hang tight :)

I did this too, lol
check the last commit, I just attached the autotagger to the page indexer

2024-07-29 15:30 UTC, zefhemel commented
Have a look at: #995

2024-07-29 17:10 UTC, zefhemel commented
> > FYI: I'm working on (1) as I proposed after all. Performance impact doesn't seem bad, hang tight :)
> 
> 
> 
> I did this too, lol
> 
> check the last commit, I just attached the autotagger to the page indexer

Right, the issue there would be that you have to reindex your entire space every time you change these "auto tag" rules. My implementation does this on the fly. It's slightly more costly at read/query time though.

2024-07-30 21:29 UTC, onespaceman commented
I think that should be it.

New example:
```
objectDecorators:
- where: 'tags = "pink"'
  attributes:
    pageDecoration.cssClass: "['make-it-pink']"
```
Make page names pink
```
.make-it-pink.sb-decorated-object {
  &,
  .sb-name,
  .cm-completionLabel {
    color: hotpink;
  }
}
```
Add pink accent border to editor
```
body.make-it-pink {
  #sb-editor .cm-content {
    border-left: solid 0.5em hotpink;
  }
}
```

At this point we kinda need a dedicated page for snippets on the site.

2024-07-30 21:34 UTC, onespaceman commented
This one might be useful enough to add as a default
```
- where: 'tag = "attachment"'
  attributes:
    pageDecoration.prefix: "'🔗 '"
```

2024-07-31 09:28 UTC, zefhemel commented
Excellent, the only thing I changed here to rename the decoration to cssClassES (because it expects a list), and added some examples (nice Christmas decoration ones).

2024-07-31 09:28 UTC, merged